// VM exercise of our own read-only public tools; no browser/network or shell actions.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const manifest = JSON.parse(fs.readFileSync('dist/mine.json', 'utf8'));
const tools = new Map();
let requests = 0;
const ctx = vm.createContext({ window: {}, document: { modelContext: { registerTool: t => tools.set(t.name, t) } }, navigator: {}, fetch: async url => { assert.equal(url, '/mine.json'); requests++; return { ok: true, json: async () => manifest }; } });
vm.runInContext(fs.readFileSync('site/assets/requirements.js', 'utf8'), ctx);
vm.runInContext(fs.readFileSync('site/webmcp.js', 'utf8'), ctx);
(async () => {
  assert.equal(tools.size, 6);
  for (const tool of tools.values()) assert.equal(tool.annotations.readOnlyHint, true);
  assert.equal((await tools.get('get_mining_status').execute()).status.live, false);
  assert.equal((await tools.get('get_agent_prompt').execute({variant: 'safe'})).prompt, manifest.prompts.safe);
  const checker = tools.get('check_requirements');
  assert.equal((await checker.execute({os:'linux',gpu_vram_gb:24})).hardware_candidate, true);
  assert.equal((await checker.execute({os:'linux',gpu_vram_gb:23})).hardware_candidate, false);
  assert.equal((await checker.execute({os:'macos',gpu_vram_gb:96})).hardware_candidate, false);
  assert.match((await checker.execute({os:'windows',gpu_vram_gb:24})).reasons.join(' '),/not yet tested by us/);
  const prelaunch = await checker.execute({os:'linux',gpu_vram_gb:0});
  assert.match(prelaunch.reasons.join(' '), /private until launch/);
  assert.doesNotMatch(prelaunch.reasons.join(' '), /Rehearse free.*today|Free rehearsal is available/);
  const prepared = await tools.get('get_setup_steps').execute({mode:'localnet'});
  assert.equal(prepared.steps.find(s => s.id === 'install').blocked_until_live, true);
  assert.match(prepared.steps.find(s => s.id === 'install').command, /install --mode localnet/);
  assert.match(prepared.steps.find(s => s.id === 'choose-mode').verify, /STOP/);
  const mainnetInstall = (await tools.get('get_setup_steps').execute({mode:'mainnet'})).steps.find(s => s.id === 'install');
  assert.match(mainnetInstall.command, /--confirm-mainnet/);
  const testnetInstall = (await tools.get('get_setup_steps').execute({mode:'testnet'})).steps.find(s => s.id === 'install');
  assert.match(testnetInstall.command, /--mode testnet/);
  assert.doesNotMatch(testnetInstall.command, /--confirm-(mainnet|testnet)/);
  const liveManifest = JSON.parse(JSON.stringify(manifest));
  liveManifest.state = 'live'; liveManifest.status.live = true; liveManifest.source.public = true;
  // Use the real live copy selected by the builder, not a test-authored verdict.
  const cp = require('node:child_process');
  liveManifest.copy = JSON.parse(cp.execFileSync('python3', ['-c', "import runpy,json; b=runpy.run_path('scripts/build.py'); print(json.dumps(b['COPY']['live']))"], {encoding:'utf8'}));
  const liveVerdict = ctx.window.MiningRequirements.check(liveManifest, 'linux', 0);
  assert.match(liveVerdict.reasons.join(' '), /test TAO before real registration/);
  assert.doesNotMatch(liveVerdict.reasons.join(' '), /private until launch|not live yet/);
  for (const os of ['linux','windows','macos']) assert.ok((await tools.get('get_wallet_guidance').execute({os})).guidance);
  const mainnet = await tools.get('get_setup_steps').execute({mode:'mainnet'});
  assert.equal(mainnet.steps.find(s => s.id==='register').who,'human');
  assert.equal(mainnet.steps.find(s => s.id==='register').blocked_until_live,true);
  assert.ok((await tools.get('get_agent_rules').execute()).rules.length >= 6);
  await assert.rejects(checker.execute({os:'other',gpu_vram_gb:24}));
  await assert.rejects(checker.execute({os:'linux',gpu_vram_gb:-1}));
  await assert.rejects(checker.execute({os:'linux',gpu_vram_gb:'24'}));
  await assert.rejects(tools.get('get_agent_prompt').execute({variant:'arbitrary'}));
  await assert.rejects(tools.get('get_setup_steps').execute({mode:'arbitrary'}));
  assert.equal(requests,1);
  let count=0;
  ctx.document.modelContext.registerTool=() => { count++; if(count===1) throw new Error('unsupported tool'); };
  vm.runInContext(fs.readFileSync('site/webmcp.js','utf8'),ctx);
  assert.equal(count,6);
  delete ctx.document.modelContext;
  ctx.navigator.modelContext={registerTool:()=>count++};
  vm.runInContext(fs.readFileSync('site/webmcp.js','utf8'),ctx);
  assert.equal(count,12);
  console.log('PASS: six read-only tools, source data, VRAM boundary, enums, cache, per-tool isolation and navigator fallback');
})().catch(e=>{console.error(e);process.exitCode=1;});
